name: 'Latest PHP Releases'
description: 'A Github Action to fetch a list of active PHP releases.'
author: 'Dominik Szamburski'

branding:
    icon: 'package'
    color: 'blue'

outputs:
    releases:
        description: A JSON array of active PHP releases, sorted by version in ascending order.

runs:
    using: node20
    main: dist/index.js
